### ISSUE TITLE
Guide "Before you start" should include react related deps as well as rust related

### ISSUE THREAD

**Issue by trevoranderson** [jhugman/uniffi-bindgen-react-native#132]
Checking out the guide as someone that is new to react native. There's references in the Step-by-step guide to tools that were not mentioned in the previous setting up tools section. I have some JS/TS familiarity so I can install them, but `npx` and `yarn` are left for the reader to figure out if they are not already installed

Also error at this step (I was having issues with `pod` so I was in the `example/ios` directory instead of the react root)
```
% yarn example start
Usage Error: Couldn't find a script named "example".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```

List of commands/tools I had to either already have or install (so far)
`npx`
`yarn`
`pod`
`Android SDK`

**Comment by Johennes** [comment]
It might be best for UBRN to just link out to https://reactnative.dev/docs/set-up-your-environment. The RN environmental does have quite a few pieces and it's probably not worth replicating and maintaining that description here.
