### ISSUE TITLE
create-react-native-library: Failed generate the codegen file

### ISSUE THREAD

**Issue by boek** [jhugman/uniffi-bindgen-react-native#138]
first time setting up a react native build on this machine following the getting started guide and ran into this error
```
/Users/jboek/Developer/tmp/rnrust/my-rust-lib/node_modules/react-native-builder-bob/lib/targets/codegen.js:48
    throw new Error('Failed generate the codegen files.');
Error: Failed generate the codegen files.
    at build (/Users/jboek/Developer/tmp/rnrust/my-rust-lib/node_modules/react-native-builder-bob/lib/targets/codegen.js:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async buildTarget (/Users/jboek/Developer/tmp/rnrust/my-rust-lib/node_modules/react-native-builder-bob/lib/index.js:421:7)
   ```
   
   Was able to get past it by adding `"@react-native-community/cli": "latest",` to my `devDependencies` in the project. We may want to either call this out as a dependency to install globally or include it in the `devDependencies` in the template.

**Comment by Johennes** [comment]
This is interesting because in https://github.com/unomed-dev/react-native-matrix-sdk/blob/main/yarn.lock#L10774 (which was generated with `create-react-native-library`) I'm getting this package as a direct dependency of react-native itself. 🤔

**Comment by jhugman** [comment]
This may be related to https://github.com/callstack/react-native-builder-bob/issues/662 , reported earlier today.

**Comment by Johennes** [comment]
Oh, great find! Unfortunately, running into regressions when integrating the various tools in the RN ecosystem is a somewhat common annoyance in my experience. 😞

Maybe we could try to pin the RN version in the guide?

**Comment by atlj** [comment]
FYI: https://github.com/callstack/react-native-builder-bob/pull/665

The fix is to add `"@react-native-community/cli": "15.0.0-alpha.2",` or with the version you desire to the root package's `devDependencies`.

**Comment by jhugman** [comment]
This appears to be fixed; thank you @atlj .

**Comment by jhugman** [comment]
> This project looks pretty interesting. If you have any other problems with CRNL or builder bob, please feel free to ping me.

Sure thing! Thank you for everything you do!
