### ISSUE TITLE
Documentation assumes I have yarn installed

### ISSUE THREAD

**Issue by boek** [jhugman/uniffi-bindgen-react-native#139]
To make things easier for people coming to RN from rust we may want to call out installing yarn in the getting started guide.

**Comment by Johennes** [comment]
It is mentioned in the pre-install guide actually: https://github.com/jhugman/uniffi-bindgen-react-native/blob/main/docs/src/guides/pre-installation.md?plain=1#L11

Maybe it needs to be repeated in the getting starting guide?

**Comment by boek** [comment]
🤦 not sure how I missed that. 

I pulled that section out into an info which might help people like me not gloss over it.

<img width="828" alt="image" src="https://github.com/user-attachments/assets/2b2822a9-e896-49d8-aa83-f86fe874151c">

**Comment by jhugman** [comment]
Fixed by #142
