### ISSUE TITLE
yarn example start silently fails on iOS when missing a development team

### ISSUE THREAD

**Issue by boek** [jhugman/uniffi-bindgen-react-native#140]
When building the project for the first time the build got stuck on

```
info Building (using "xcodebuild -workspace RustOrBustExample.xcworkspace -configuration Debug -scheme RustOrBustExample -destination id=00008120-001A5DA402DB401E")
```

second time running it under verbose I found the error

```
error Signing for "RustOrBustExample" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'RustOrBustExample' from project 'RustOrBustExample')
error Failed to build ios project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'RustOrBustExample.xcworkspace'.
```

Not sure if I prematurely cancelled it the first time and something else happened. Will try to repro again.

**Comment by Johennes** [comment]
I think this plays into https://github.com/jhugman/uniffi-bindgen-react-native/issues/141. Code signing and picking a development team should only be needed when you're building for a physical device.
