### ISSUE TITLE
Add yarn.lock to version control?

### ISSUE THREAD

**Issue by Johennes** [jhugman/uniffi-bindgen-react-native#170]
In https://github.com/jhugman/uniffi-bindgen-react-native/pull/168#issuecomment-2512391838 we discussed whether or not to add yarn's lock file to version control. Apparently there is different guidance on this online. https://github.com/yarnpkg/yarn/issues/838#issuecomment-253362537 advises against it whereas the [yarn (classic) docs](https://classic.yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control) say the opposite. Adding the lock file would enable reproducible tests but might have downsides that we should figure out.

**Comment by jhugman** [comment]
Looking at these links (and [this one](https://yarnpkg.com/getting-started/qa#should-lockfiles-be-committed-to-the-repository)) I think I'm convinced we should do this.
