### ISSUE TITLE
Less silence from the CLI when ran the first time

### ISSUE THREAD

**Issue by kraenhansen** [jhugman/uniffi-bindgen-react-native#181]
Since the CLI is calling into [cargo run](https://github.com/jhugman/uniffi-bindgen-react-native/blob/56a74a521f9294af77ace1bcf44eb707ccf38b5e/bin/cli.cjs#L43) it takes quite a bit of time on the initial call (as dependencies needs to be downloaded and CLI has to be built). While I agree that I don't want this feedback on every call and passing the `--quite` flag makes sense in that case, it would be great to get some sort of feedback when called initially.

A naive solution would be to check for the existence of the `target` directory and log something about "Building the CLI".

**Comment by Johennes** [comment]
This sounds like a great idea. I also wouldn't mind if it just always printed out the cargo run command (though that might be a weaker indicator of something being built).

**Comment by kraenhansen** [comment]
> if it just always printed out the cargo run command

Yeah, actually. That would show this is using Rust under the hood, but that's fine for a build tool like this 👍 The output on subsequent runs are also fairly limited and it'll be much less confusing than waiting for _something_ to happen on the initial run.
