### ISSUE TITLE
Allow specifying the profile for cargo build

### ISSUE THREAD

**Issue by Johennes** [jhugman/uniffi-bindgen-react-native#190]
Following through from https://github.com/matrix-org/matrix-rust-sdk/issues/4416, matrix-rust-sdk uses the `reldbg` profile by [default](https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs#L70). This cannot be selected via UBRN though because we only have a `--release` flag that [switches](https://github.com/jhugman/uniffi-bindgen-react-native/blob/main/crates/ubrn_common/src/rust_crate.rs#L25) between the `debug` and `release` profiles.

Adding `--profile reldbg` via `cargoExtras` does not work because UBRN will still look for the library under the `debug` or `release` folder.

Proposal: Add a `profile` config / CLI option to select the specific profile. If both `profile` and `release` are specified, let `profile` take precedence ([as in matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/blob/main/xtask/src/swift.rs#L31)).

**Comment by jhugman** [comment]
This is a good idea, thanks for suggesting it!

It looks like it shouldn't be too difficult to add.

The [`CommonBuildArgs` struct](https://github.com/jhugman/uniffi-bindgen-react-native/blob/0ea522e614621b56cb9ae4af508deccc74b30d52/crates/ubrn_cli/src/building.rs#L84-L107).

Adding an additional `profile` attribute:

```rs
    /// Suitable documentation
    #[clap(long, conflicts_with_all = ["release"]]
    profile: Option<String>,
```

and adapting the existing `fn profile(&self)` might be all you need. 

I checked: the [android `cargo ndk` command](https://github.com/jhugman/uniffi-bindgen-react-native/blob/0ea522e614621b56cb9ae4af508deccc74b30d52/crates/ubrn_cli/src/android.rs#L235-L241) needs to change, as does [the `cargo build` for iOS](https://github.com/jhugman/uniffi-bindgen-react-native/blob/0ea522e614621b56cb9ae4af508deccc74b30d52/crates/ubrn_cli/src/ios.rs#L210-L218).

I'm unlikely to get to this before next month, however. Would you like to pick this up, or would you like to wait?

**Comment by Johennes** [comment]
Thanks for the pointers. ❤️ 

I took a stab at it in https://github.com/jhugman/uniffi-bindgen-react-native/pull/192.
