### ISSUE TITLE
Improvement for callstacks with async function

### ISSUE THREAD

**Issue by zzorba** [jhugman/uniffi-bindgen-react-native#79]
Today, an async function generates code like this:

```
  public async getMediaContent(
    mediaSource: MediaSourceInterface
  ): Promise<ArrayBuffer> /*throws*/ {
    return await uniffiRustCallAsync(
      /*rustFutureFunc:*/ () => {
        return nativeModule().uniffi_matrix_sdk_ffi_fn_method_client_get_media_content(
          uniffiTypeClientObjectFactory.clonePointer(this),
          FfiConverterTypeMediaSource.lower(mediaSource)
        );
      },
      /*pollFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_poll_rust_buffer,
      /*cancelFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_cancel_rust_buffer,
      /*completeFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_complete_rust_buffer,
      /*freeFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_free_rust_buffer,
      /*liftFunc:*/ FfiConverterArrayBuffer.lift.bind(FfiConverterArrayBuffer),
      /*liftString:*/ FfiConverterString.lift,
      /*errorHandler:*/ FfiConverterTypeClientError.lift.bind(
        FfiConverterTypeClientError
      )
    );
  }
  ```
  
  Unfortunately, this means that if an error is returned, it will appear in the asyncDispatcher in hermes, with very little callstack present.
  
  I believe that if we changed the generated code to include a try/catch/rethrow and an await, it would at least let us locate the error to the calling async function, instead of in a random part of the underlying system.
  
  ```
  public async getMediaContent(
    mediaSource: MediaSourceInterface
  ): Promise<ArrayBuffer> /*throws*/ {
+ try {
    return await uniffiRustCallAsync(
      /*rustFutureFunc:*/ () => {
        return nativeModule().uniffi_matrix_sdk_ffi_fn_method_client_get_media_content(
          uniffiTypeClientObjectFactory.clonePointer(this),
          FfiConverterTypeMediaSource.lower(mediaSource)
        );
      },
      /*pollFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_poll_rust_buffer,
      /*cancelFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_cancel_rust_buffer,
      /*completeFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_complete_rust_buffer,
      /*freeFunc:*/ nativeModule()
        .ffi_matrix_sdk_ffi_rust_future_free_rust_buffer,
      /*liftFunc:*/ FfiConverterArrayBuffer.lift.bind(FfiConverterArrayBuffer),
      /*liftString:*/ FfiConverterString.lift,
      /*errorHandler:*/ FfiConverterTypeClientError.lift.bind(
        FfiConverterTypeClientError
      )
    );
  + } catch (e) {
  + throw e;
  + }
  }
  ```

This would make the errors a lot more actionable and would probably lead to a lot fewer false positives.

**Comment by jhugman** [comment]
I started implementing this, as you suggest:

```typescript
        try {
            return await uniffiRustCallAsync(…)
        } catch (e: any) {
            throw e;
        }
```

Anything error generated after the first `await` has a stack that does not include the caller.

According to [this 2017 article from a V8 developer](https://mathiasbynens.be/notes/async-stack-traces):

> To make it work, the JavaScript engine needs to do something in addition to the above steps: **it captures and stores the stack trace within a while it still has the chance**. In V8, the stack trace is attached to the promise that b returns. 
> […]
> Capturing the stack trace takes time (i.e. degrades performance); storing these stack traces requires memory.

(_emphasis mine_)

This corresponds to:

```typescript
        const _stack = new Error().stack!;
        try {
            return await uniffiRustCallAsync(…)
        } catch (e: any) {
            if (e instanceof Error) {
                e.stack = _stack;
            }
            throw e;
        }
```

This is a relatively easy intervention, but is it the right one?

- Does hermes normally produce sensible stack traces after an `await`? Are we somehow disrupting that ability in our generated code? (paging @zzorba, or any sufficiently experienced RN developer)
- How much of a performance loss is this? We desperately need performance measurement fixtures to measure the impact of such a change.


@zzorba wdyt?

**Comment by zzorba** [comment]
Theoretically we'd only pay a performance penalty for this when an exception is actually being thrown right?  I guess you can technically use exceptions for normal flow of data (and in a Result bridge from Rust it might be more common)?

Is this something we could enable in Debug-mode only, and remove in release mode?
